### ISSUE TITLE
Very Low RSSI at the base station running on SDRplay

### ISSUE THREAD

**Issue by OmidKandelusy** [loriot/miotyGO#2]
Hi there,

I implemented the Mioty network using the Raspberry PIs.
For the sensor endpoint side I am using a Pico Pi with RFM69HCW which works well, as I tested using a spectrum analyzer; it transmits with a max Tx power of 14dBm.

However, on the Base station side where the SDRplay is used for the RF module, the receiver signal strength indicator (RSSI) is very low: -70 dBm for a distance of 50 cm. I tried to measure the received power with spectrum analyzer and the received signal is way stronger than what the base station repots as the RSSI.

So, I believe something does not work properly on the base station side which runs on the SDR play. Any help or suggestions is much appreciated.

Thanks.

**Comment by lorryOT** [comment]
Hi there, 

We have taken a look to the issue and the problem seems to be related to the power gain being set to the RSP device, on more recent versions we are adding a new field to the config json called "Rx_power_dBm which represents the RX power in dBm set to the device, by default is set to -65 but you can try to adjust this field depending of the requirements.

Now the config json under `/etc/miotyGO/config.json` looks like this:
```
{
    "ServiceCenter": "eu3.loriot.io",
    "ServiceCenterPort": "727",
    "Profile": "eu868",
    "RX_power_dBm": -65,
    "bssid": ""
}
```
You can run the installer again or only replace the binary and add this new field to the config.json manually.

Right now the solution is available on the branch attached to this issue so if you run the installer from [this branch]() you should be able to run this new version, hopefully we will publish this solution in the next release soon.

Thank you for contacting us and let us know if there are something else we can try to solve.

Loriot team.

**Comment by OmidKandelusy** [comment]
Hi there, thanks for your prompt response.
Since then I was tinkering with the new branch, but still there is an issue.

It seems like the radio communication itself is working and the actual received signal strength is different from what is shown in logs. The reason I am saying that is that I tested two very different distances and I get almost the same RSSI readings!!

**NOTE:** I am using a simple 2dBi omnidirectional rubber duck antenna for the SDR and a simple 2 dBi PCB antenna for the end point device. (Also, the receiver gain in the JSON file was set to 10 dBm and 0 dBm)

here is the logs for two experiments one far distance and near distance:

Near distance (**1.5 meters** distance between the transmitter and receiver):
![mioty_rssi_closedistance](https://github.com/user-attachments/assets/d71724c8-0b85-41b2-83e3-e03231166c3b)

Far distance (**more than 40 meters** distance between the transmitter and receiver):
![mioty_rssi_fardistance](https://github.com/user-attachments/assets/ce511982-19d2-47a1-8e1c-827667b11eaa)

**Comment by lorryOT** [comment]
Hi there, fist of all, sorry for this late answer.

We have tested again the last release attached to this version and these are our results:

First test was with value **40 for the field RX_power** as shown in the code attached, with this value we got a RSSI value about **-40 dBm.**
```
{
    "ServiceCenter": "eu3.loriot.io",
    "ServiceCenterPort": "727",
    "Profile": "eu868",
    "RX_power_dBm": 40,
    "bssid": ""
}
```
![image](https://github.com/user-attachments/assets/4e9a12c3-bb0e-4631-b46a-4309e27a8353)

Same test using the same software but changing the **RX_power to 100** as shown in the screenshot increase the **RSSI value to almost 20 dBm**
```
{
    "ServiceCenter": "eu3.loriot.io",
    "ServiceCenterPort": "727",
    "Profile": "eu868",
    "RX_power_dBm": 100,
    "bssid": ""
}
```
![image](https://github.com/user-attachments/assets/c4607a08-cfa8-4b7b-87b6-0916e9116bed)

We are still working on a final solution to this issue and also updating the docs. In the meantime we would suggest to increase even more "RX_power" value to see if you can also increase RSSI value. During this time, any feedback we receive will be gratefully received, and if we can help with anything else, we will be happy to do so.

Thank you again for contacting us.

Loriot team.

**Comment by lorryOT** [comment]
Closed due to inactivity.
